server:
  port: 8082 #le puse 8082 pq el 8080 está en jenkins
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost/eureka}
  #instance:
  #  hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: HU1-service
          uri: lb://HU1-service
          predicates:
            - Path=/ingreso_salida/**
        - id: HU2-service
          uri: lb://HU2-service
          predicates:
            - Path=/inasistencia/**
        - id: HU3-service
          uri: lb://HU3-service
          predicates:
            - Path=/autorizacion/**
        - id: HU4-service
          uri: lb://HU4-service
          predicates:
            - Path=/sueldo/**
        - id: HU5-service
          uri: lb://HU5-service
          predicates:
            - Path=/empleado/**
        