server:
  port: 8082 #le puse 8082 pq el 8080 está en jenkins
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost/eureka}
  #instance:
  #  hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: HU1
          uri: lb://HU1
          predicates:
            - Path=/ingreso_salida